### PR TITLE
Undefined name: import zipfile for line 18 and 36

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by jeff5** [comment]
Hi @cclauss. What do you make of the comment just after that says zipfile is magically inserted?

It says ``jpython.java``, but I think it means ``jython.java``. (It must be very old code.)
https://github.com/jython/jython/blob/master/src/org/python/util/jython.java#L217

**Comment by cclauss** [comment]
> zipfile is magically inserted

Magic is something that production code should not rely on.  _Explicit is better than implicit._

If some other file has already imported zipfile then `'zipfile' in sys.modules` may be True however is that something that you want to rely on?  If those other files are changed then the magic suddenly disappears and a NameError will be raised on our users at runtime.

**Comment by jeff5** [comment]
Sure, but if you look at *what* `zipfile` is magically bound to, you'll find it's not the module called `zipfile` but an actual Zip file.

There's nothing wrong with this code except that it is confusing to the reader (and maybe your linter).

A less confusing expression of the intent would be to assign `zipfile = None` and update the comment that it supports the `-jar` option and `org.python.util.jython` will supply it by extra-pythonic assignment.

**Comment by jeff5** [comment]
@cclauss : This file mostly needs updates to the comments, but I'll include the flake directive too. (In fact it needs two, see https://github.com/jython/jython/commit/7a0323eea2500974c9254e6914528f4ba43515ae.) Thanks for spotting it.

**Pull request closed without merging**
